#! /bin/sh

#bspc monitor -d ➊ ➋ ➌ ➍ ➎ ➏ ➐ ➑ ➒ ➓
bspc monitor -d a b c d e f g h i k

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config top_padding 10
bspc config bottom_padding 10

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Iceweasel desktop=^2
bspc rule -a Surf desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off

rm -f $PANEL_FIFO
mkfifo $PANEL_FIFO
(sleep 2 && ~/.config/bspwm/panel/panel ) &
