[[ -d $HOME/bin ]] && export PATH=$HOME/bin:$PATH

# Almost decidedly wrong - will investigate
export TERMINAL="urxvt"
export EDITOR="vim"
export GOPATH="$HOME/build/go/";
export WORKLOGDIR="$HOME/.worklog";
export LEDGER_FILE=$HOME/ledger.dat
export TIMELOG=$HOME/ledger.dat
